# Generated by Django 3.1.6 on 2021-02-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ManyToManyField(to='main.AuthorModel')),
            ],
        ),
        migrations.CreateModel(
            name='GanreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bookmodel')),
                ('image', models.ManyToManyField(to='main.ImageModel')),
            ],
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='ganre',
            field=models.ManyToManyField(to='main.GanreModel'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.publishedmodel'),
        ),
    ]
